### ISSUE TITLE
Icon in the dock is vertically skewed !

### ISSUE THREAD

**Issue by aiamuzz** [CareF/deepin-dock-plugin-weather#3]
@CareF ... the icon in the weather menu are perfectly round ... where as the icon which is placed in the dock seems skewed somehow ... its either stretched horizontally or its reduced vertically ... it doesn't seem a circle, more of a horizontal ellipse ... 

for comparison look how the power plugin icon and the date time icon are perfectly round and circular !

**Comment by CareF** [comment]
Not sure what you mean. Is it possible that you can post a screenshot?

**Comment by aiamuzz** [comment]
the plugin icons for power and data/time are circular height is equal to the width ... the icon for weather is an ellipse ... **height is less than width ...** ...

please note this is only for the icon in the dock ... the icons in the weather menu are perfect !!!

![deepinscreenshot_select-area_20190105145200](https://user-images.githubusercontent.com/3283676/50722734-7ce82300-10f9-11e9-8298-8c4094b8a054.png)

**Comment by CareF** [comment]
I pushed a commit (https://github.com/CareF/deepin-dock-plugin-weather/commit/5446c374cb5d4e15ccf67624c1868e6445b85203) to fix it. 
I have to say that the original code is not the way I would program it, and the fix is kind of a dirty trick. 
In the long run I may probably reprogram it... if I have time...

**Comment by CareF** [comment]
https://github.com/CareF/deepin-dock-plugin-weather/commit/5446c374cb5d4e15ccf67624c1868e6445b85203 
unless it's not fixed

**Comment by CareF** [comment]
And I haven't tag the change or upload binary file, so to test you have to compile it locally. 

Let me know if it looks fine on your computer.

**Comment by aiamuzz** [comment]
hmmmm ... i just downloaded the zip file and tried compiling it ... encountered the following error ...

```
qmake ..
muz@AH15:~/Downloads/linuxPackagesBuildnInstall/Plugins/Weather/deepin-dock-plugin-weather-master/build$ make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I../../deepin-dock-plugin-weather-master -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I/usr/include/libdtk-2.0.9/DWidget -I/usr/include/libdtk-2.0.9/DCore -I. -I../../deepin-dock-plugin-weather-master -I. -o weatherplugin.o ../weatherplugin.cpp
In file included from ../weatherplugin.cpp:1:0:
../weatherplugin.h:4:10: fatal error: dde-dock/pluginsiteminterface.h: No such file or directory
 #include "dde-dock/pluginsiteminterface.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:240: weatherplugin.o] Error 1

```

**Comment by aiamuzz** [comment]
Yup !
It worked the icon aspect ration is intact ... it no longer is an ellipse !
:)

![deepinscreenshot_select-area_20190107233944](https://user-images.githubusercontent.com/3283676/50785080-8f1eb880-12d5-11e9-829f-ac7f066e25c3.png)

**Comment by sonichy** [comment]
Wonderful......

**Comment by sonichy** [comment]
I found the reason:
QPainter::drawPixmap(const QRect &rectangle, const QPixmap &pixmap)
Note: The pixmap is scaled to fit the rectangle, if both the pixmap and rectangle size disagree.
So, get the smaller of rect(), define a new rect to draw in.
````
int w = qMin(width(), height());
int x = (width() - w) / 2;
int y = (height() - w) / 2;
QRect rect1(x, y, w, w);
painter.drawPixmap(rect1, pixmap);
````
If you want to scale, refer to the shutdown plugin
````
int w = qMin(width(), height());
pixmap = pixmap.scaled(w*0.8, w*0.8, Qt::KeepAspectRatio, Qt::SmoothTransformation);
painter.drawPixmap(rect().center() - pixmap.rect().center(), pixmap);
````
